### ISSUE TITLE
serokell/snowdrop dependency is missing

### ISSUE THREAD

**Issue by clojurians-org** [DisciplinaOU/disciplina#18]
when i build this project with "stack build": 
 it can't download the serokell/snowdrop dependency successfully. 
i can't find the library in serokell repositories also.

**Comment by flyingleafe** [comment]
Latest release of Disciplina (https://github.com/DisciplinaOU/disciplina/releases/tag/v0.1.0-alpha) no longer depends on any private repos (`serokell/snowdrop` dependency is replaced with `serokell/blockchain-util` dependency).
